name: 'SmartCoder Code review'
description: 'Code review using SmartCoder'
author: 'SmartCoder.org'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  SMART_CODER_API_URL:
    description: "SmartCoder api url."
    required: true
  SMART_CODER_API_KEY:
    description: "API key for SmartCoder."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""

runs:
  using: node20
  main: dist/index.js
