# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build.
name: Code Review Action

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      - name: Code Review
        id: code-review
        uses: ./
        with:
          GITHUB_TOKEN: ${{ github.token }}
          SMART_CODER_API_URL: ${{ vars.SMART_CODER_API_URL }}
          SMART_CODER_API_KEY: ${{ secrets.SMART_CODER_API_KEY }}
          exclude: "yarn.lock,dist/**"

      
